name: "HCL AppScan CodeSweep"
on:
  pull_request:
    types: [opened,synchronize]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run AppScan CodeSweep
        uses: HCL-TECH-SOFTWARE/appscan-codesweep-action@v2
        with:
          asoc_key: "84ee6a2f-8ba7-cbf4-0c6e-dd5f9bc8b2f2"
          asoc_secret: "JjhyPfw7QmAU3IRSrKKSfRXaKS0cvrX0phnYZc10uEPz"
    env: 
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
